

- name: install required packages
  package:
    state: latest
    name: 
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

- name: add repo
  shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"

- name: install docker
  package: 
    name: docker-ce-18.06.2.ce
    state: installed

- name: prevent yum from updating docker
  lineinfile:
    path: /etc/yum.conf
    line: "exclude=docker-ce"
    regexp: ^exclude=docke

- file: state=directory path=/etc/docker
- file: state=directory path=/etc/systemd/system.docker.service.d

- name: force docker to use systemd and not cgroupfs
  copy:
    content: |
             {
               "exec-opts": ["native.cgroupdriver=systemd"],
               "log-driver": "json-file",
               "log-opts": {
                 "max-size": "100m"
               },
               "storage-driver": "overlay2",
               "storage-opts": [
                 "overlay2.override_kernel_check=true"
               ]
             }
    dest: /etc/docker/daemon.json

- name: read configs
  shell: systemctl daemon-reload

- name: start and enabled docker
  service: 
    name: docker
    state: started
    enabled: true

